### ISSUE TITLE
Add page titles

### ISSUE THREAD

**Issue by delphidabbler** [cahamo/cahamo.github.io#26]
Few, if any, pages have a `<title>` set other than the default.

Titles really are needed for SEO.

Code has been written to use any title that is set in a page's front matter, e.g.

```yaml
---
layout: default
title: "My Page Title"
---
```
